# Generated by Django 4.2.4 on 2023-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
