# Generated by Django 4.2.4 on 2023-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
